DROP DATABASE IF EXISTS planitDB;
CREATE DATABASE planitDB;

USE planitDB;

CREATE TABLE `event`(
    `id` INTEGER AUTO_INCREMENT NOT NULL,
    `moment` VARCHAR(13),
    `event` VARCHAR(30) NOT NULL,
    `month` INTEGER NOT NULL,
    `day` INTEGER NOT NULL,
    `finished` BOOLEAN NOT NULL DEFAULT FALSE,
    `important` BOOLEAN NOT NULL DEFAULT FALSE ,
    PRIMARY KEY(id)
);

CREATE TABLE user_info(
    `id` INTEGER AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(30) NOT NULL,
    `email` VARCHAR(60) NOT NULL,
    `password` VARCHAR NOT NULL,
    PRIMARY KEY(id)
);
